### ISSUE TITLE
undefined method to_r on ruby 1.8

### ISSUE THREAD

**Issue by grosser** [travisjeffery/timecop#101]
0.6.1 worked fine

```
/Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/timecop-0.6.2/lib/timecop/time_stack_item.rb:54:in `time': undefined method `to_r' for Sat Jul 20 01:45:03 UTC 2013:Time (NoMethodError)
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/timecop-0.6.2/lib/timecop/time_extensions.rb:7:in `mock_time'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/timecop-0.6.2/lib/timecop/time_extensions.rb:13:in `now'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/test-unit-2.5.
```

**Comment by packrat386** [comment]
:(

**Comment by grosser** [comment]
stop using ruby 1.8 dammit :D
