### ISSUE TITLE
undefined method `to_r` on Timecop.travel

### ISSUE THREAD

**Issue by ghiculescu** [travisjeffery/timecop#103]
I'm getting the following error:

```
$ rails console
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.7.8
Connecting to database specified by database.yml
Loading development environment (Rails 3.2.12)
1.9.3p286 :001 > Timecop.travel(Time.zone.parse(Date::DAYNAMES.first))
NoMethodError: undefined method `to_r' for Sat, 27 Jul 2013 14:00:00 +0000:DateTime
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/timecop-0.6.2.2/lib/timecop/time_stack_item.rb:54:in `time'
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/timecop-0.6.2.2/lib/timecop/time_stack_item.rb:129:in `compute_travel_offset'
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/timecop-0.6.2.2/lib/timecop/time_stack_item.rb:13:in `initialize'
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/timecop-0.6.2.2/lib/timecop/timecop.rb:124:in `new'
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/timecop-0.6.2.2/lib/timecop/timecop.rb:124:in `travel'
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/timecop-0.6.2.2/lib/timecop/timecop.rb:107:in `send_travel'
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/timecop-0.6.2.2/lib/timecop/timecop.rb:61:in `travel'
    from (irb):1
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.12/lib/rails/commands/console.rb:47:in `start'
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.12/lib/rails/commands/console.rb:8:in `start'
    from /Users/alexghiculescu/.rvm/gems/ruby-1.9.3-p286/gems/railties-3.2.12/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Though I'm not sure it's a Timecop issue, given this works:

```
$ irb
1.9.3p286 :001 > require 'timecop'
 => true
1.9.3p286 :002 > require 'active_support/time'
t => true
1.9.3p286 :003 > Time.zone = 'Brisbane'
 => "Brisbane"
1.9.3p286 :004 > Timecop.travel(Time.zone.parse(Date::DAYNAMES.first))
 => 2013-07-28 00:00:00 +1000
```

That said, there is something that could be a problem. Lines 53 and 54 of `time_stack_item.rb`:

```
if @time.respond_to?(:in_time_zone)
    time = time_klass.at(@time.utc.to_r)
```

If `@time.utc` returns a `DateTime` (as it does in my `rails console` example, but not in my `irb` example - where it returns a `Time`) then this fails as `DateTime#to_r` isn't defined.

I'm not sure if this assumption is invalid or if there is something else screwy in my environment but I figured it was worth raising just in case.

**Comment by jordanmaguire** [comment]
For any future people reading this, I had the same issue.

Can call `.to_datetime` on the object to convert it to a format that plays nice with Timecop

**Comment by parreirat** [comment]
Thanks, @jordanmaguire, was quite helpful. :)
