### ISSUE TITLE
Timecop v0.7.2 breakage with ActiveSupport v4.1.9

### ISSUE THREAD

**Issue by baburdick** [travisjeffery/timecop#140]
There's an arg mismatch:
```ruby
# timecop-0.7.2/lib/timecop/time_extensions.rb
class Date
  class << self
    def parse_with_mock_date(str)
      if WEEKDAYS.keys.include?(str.downcase)
        offset = WEEKDAYS[str.downcase] - Date.today.wday

        Date.today + offset
      else
        parse_without_mock_date(str)
      end
    end

    alias_method :parse_without_mock_date, :parse
    alias_method :parse, :parse_with_mock_date
  end
end
```
```ruby
# activesupport-4.1.9/lib/active_support/core_ext/string/conversions.rb
class String
  def to_date
    ::Date.parse(self, false) unless blank?
  end
end
```
These collaborate to produce this error:
```
ArgumentError:
 wrong number of arguments (2 for 1)
# ~/.rvm/gems/ruby-2.1.2@application_core/gems/timecop-0.7.2/lib/timecop/time_extensions.rb:67:in `parse_with_mock_date'
# ~/.rvm/gems/ruby-2.1.2@application_core/gems/activesupport-4.1.9/lib/active_support/core_ext/string/conversions.rb:44:in `to_date'
# ./app/foo.rb:104:in `bar'
```

**Comment by ThomasKoppensteiner** [comment]
Please look at this Pull-Request: https://github.com/travisjeffery/timecop/pull/138

**Comment by baburdick** [comment]
Thanks. travisjeffery/timecop#138 looks good to me.

**Comment by travisjeffery** [comment]
Sweet thanks, guys.

**Comment by baburdick** [comment]
Works. My tests are passing with v0.7.3. Thanks @travisjeffery.
