### ISSUE TITLE
Failure/Error: parse_without_mock_date(*args) using ActiveSupport 4.0.0

### ISSUE THREAD

**Issue by ghost** [travisjeffery/timecop#190]
While upgrading a Rails 3.22 project to 4.0.0, we are encountering and issue where `parse_without_mock_date(*args)` is blowing up on every single spec. The version of Timecop we are coming from is 0.7.1, and the version we are attempting to upgrade to is 0.7.1. Downgrading to 0.7.1 does not fix the issue.

Here is the stack trace:

``` Ruby
Failure/Error: parse_without_mock_date(*args)

      ArgumentError:
        invalid date
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/timecop-0.8.1/lib/timecop/time_extensions.rb:108:in `parse'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/timecop-0.8.1/lib/timecop/time_extensions.rb:108:in `parse_with_mock_date'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activesupport-4.0.0/lib/active_support/core_ext/string/conversions.rb:53:in `to_datetime'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activesupport-4.0.0/lib/active_support/core_ext/date_time/calculations.rb:161:in `<=>'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activesupport-4.0.0/lib/active_support/core_ext/time/calculations.rb:281:in `compare_with_coercion'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:570:in `=='
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:570:in `block (2 levels) in table_rows'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:569:in `each'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:569:in `block in table_rows'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:557:in `each'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:557:in `map'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:557:in `table_rows'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:473:in `block (3 levels) in create_fixtures'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:471:in `each'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:471:in `block (2 levels) in create_fixtures'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:470:in `block in create_fixtures'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-oracle_enhanced-adapter-1.5.0/lib/active_record/connection_adapters/oracle_enhanced_schema_statements_ext.rb:210:in `disable_referential_integr
ity'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:457:in `create_fixtures'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:899:in `load_fixtures'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:870:in `setup_fixtures'
      # /home/adam/.rvm/gems/ruby-2.3.1@rsam-rails3/gems/activerecord-4.0.0/lib/active_record/fixtures.rb:712:in `before_setup'
```

**Comment by Budincsevity** [comment]
I'm facing with a similar issue with Ruby 2.3.6, Rails 4.0 and timecop 0.9.1. 
Have you found a solution to this problem? I would much appreciate it.
